import React from 'react'

import './serverscss/users.scss'

export default class Serverusers extends React.Component{
    render(){
        return (
            <div className="k_user">
                <table className="table">
                    <thead>
                        <tr>
                            <th>用户名</th>
                            <th>密码</th>
                            <th>密码</th>
                            <th>密码</th>
                            <th>密码</th>
                            <th>密码</th>
                            <th>密码</th>
                        </tr>
                    </thead>
                    <div className="tableBox">
                        <tbody>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>

                            
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>

                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>

                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr><tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                            <tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr><tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr><tr>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>张三</td>
                                <td>密码</td>
                                <td>18777953333</td>
                                <td>阿萨德会卡死</td>
                            </tr>
                        </tbody>
                    </div>
                </table>
            </div>
        )
    }
}